services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "443:443"
        networks:
            - custom_net
        build:
            context: requirements/nginx
    mariadb:
        container_name: mariadb
        image: mariadb
        secrets:
            - token
        networks:
            - custom_net
        build:
            context: requirements/mariadb
    wordpress:
        container_name: wordpress
        image: wordpress
        networks:
            - custom_net
        build:
            context: requirements/wordpress

networks:
    custom_net:
        driver: bridge

secrets:
    token:
        environment: "HOME"
