services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "443:443"
        networks:
            - custom_net
        build:
            context: requirements/nginx
        volumes:
            - wordpress:/var/www/wordpress
    mariadb:
        container_name: mariadb
        image: mariadb
        secrets:
            - token
        networks:
            - custom_net
        build:
            context: requirements/mariadb
        volumes:
            - mariadb:/var/lib/mysql
    wordpress:
        container_name: wordpress
        image: wordpress
        networks:
            - custom_net
        build:
            context: requirements/wordpress
        volumes:
           - wordpress:/var/www/wordpress 

volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/edarnand/data/mariadb
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/edarnand/data/wordpress

networks:
    custom_net:
        driver: bridge

secrets:
    token:
        environment: "HOME"
